version: '2.2'
services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
  #   container_name: elasticsearch
  #   environment:
  #     - http.host=0.0.0.0
  #     - transport.host=0.0.0.0    
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   mem_limit: 2g
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - ./dockerconfig/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml        
  #   ports:
  #     - 9200:9200
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.6.1
  #   container_name: kibana
  #   environment:
  #     - SERVER_NAME=kibana
  #     - SERVER_HOST=0.0.0.0
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  unichem:
    build: Docker/.
    container_name: unichem
    image: arcebi/unichem2index
    volumes:
      - ./build/unichem2index.log:/opt/unichem/unichem2index.log
      - ./build/config.yaml:/opt/unichem/config.yaml
    entrypoint: ["./unichem2index"]
  # oradbxe:
  #   image: wnameless/oracle-xe-11g
  #   container_name: oradb
  #   ports:
  #     - 1521:1521
  #   shm_size: 2gb
  #   volumes:
  #     - ./dockerconfig/configure.sql:/docker-entrypoint-initdb.d/configure.sql

