# Oracle Connection String for Unichems DB
oracleconn: ''

# ElasticSearch host, index and type
elastichost: ''
index: Unichem
type: Compound

queryranges:
  - start: 0
    finish: 50000000
  - start: 50000000
    finish: 100000000
  - start: 100000000
    finish: 160000000

# Elastic Bulk add parameters
bulklimit: 2000 # Limit of records to add for each Bulk worker
maxbulkcalls: 13 # Maximum number of worker at one time

logpath: ''
