# Oracle Connection String for Unichems DB
oracleconn: ''

# ElasticSearch host, index and type
elastichost: ''

index: Unichem
type: Compound

querymax:
  start: 0
  finish: 60000000

# Maximum amount of active queries to the DB
maxconcurrent: 5
maxattempts: 4
interval: 5000000

# Select fields must remain the same always
# Do not include semicolons

query: >
  SELECT
    ucpa.UCI,
    ucpa.STANDARDINCHI,
    ucpa.STANDARDINCHIKEY,
    ucpa.PARENT_SMILES,
    xref.SRC_COMPOUND_ID,
    so.src_id,
    so.NAME_LONG,
    so.NAME_LABEL,
    so.DESCRIPTION,
    so.BASE_ID_URL
  FROM
    TEMP_XREF xref,
    UC_SOURCE@reader1dblink so,
    (
      SELECT
        uc.UCI,
        uc.STANDARDINCHI,
        uc.STANDARDINCHIKEY,
        pa.PARENT_SMILES
      FROM
      (
        SELECT UCI, STANDARDINCHI, STANDARDINCHIKEY
        FROM TEMP_UCI
        WHERE UCI >= %d
        AND UCI < %d
      ) uc
      LEFT JOIN SS_PARENTS pa ON pa.UCI = uc.UCI
    ) ucpa
  WHERE xref.ASSIGNMENT = 1
  AND xref.UCI = ucpa.UCI
  AND xref.src_id = so.src_id
  ORDER BY ucpa.UCI

# Elastic Bulk add parameters
bulklimit: 2000 # Limit of records to add for each Bulk worker
maxbulkcalls: 10 # Maximum number of worker at one time


logpath: 'build/logs/'