# Oracle Connection String for Unichems DB
oracleconn: ''

# ElasticSearch host, index and type
elastichost: ''

index: Unichem
type: Compound

# Total range of UCIs to fetch from the database plus interval
querymax:
  start: 0
  finish: 60000000

elasticauth:
  username: user
  password: pass
# Maximum amount of active queries to the DB
maxconcurrent: 5
maxattempts: 4
interval: 5000000

# Select fields must remain the same always
# Do not include semicolons

query: >
  SELECT
      ucpa.UCI,
      ucpa.STANDARDINCHI,
      ucpa.STANDARDINCHIKEY,
      ucpa.PARENT_SMILES,
      xref.SRC_COMPOUND_ID,
      xref.ASSIGNMENT,
      xref.CREATED,
      xref.LASTUPDATED,
      so.src_id,
      so.NAME_LONG,
      so.NAME_LABEL,
      so.DESCRIPTION,
      so.BASE_ID_URL,
      so.NAME,
      so.BASE_ID_URL_AVAILABLE,
      so.AUX_FOR_URL,
      so.PRIVATE
  FROM
  UC_XREF xref,
  UC_SOURCE so,
  (
      SELECT UCI, STANDARDINCHI, STANDARDINCHIKEY, PARENT_SMILES
      FROM UC_STRUCTURE
      WHERE UCI >= %d
      AND UCI < %d
  ) ucpa
  WHERE xref.UCI = ucpa.UCI
  AND xref.src_id = so.src_id
  ORDER BY ucpa.UCI

# Elastic Bulk add parameters
bulklimit: 2000 # Limit of records to add for each Bulk worker
maxbulkcalls: 10 # Maximum number of worker at one time


logpath: 'build/logs/'